const SET_POSTS = 'SET_POSTS';
const LOAD_POSTS = 'LOAD_POSTS';
const SET_POSTS_LIMIT = 'SET_POSTS_LIMIT';
const LOAD_SELECTED_POST = 'LOAD_SELECTED_POST';
const SET_SELECTED_POST = 'SET_SELECTED_POST';
const SET_TOTAL = 'SET_TOTAL';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_CURRENT_POST = 'SET_CURRENT_POST'
const ADD_POST = 'ADD_POST'

export {
    SET_POSTS,
    LOAD_POSTS,
    SET_POSTS_LIMIT,
    LOAD_SELECTED_POST,
    SET_SELECTED_POST,
    SET_TOTAL,
    SET_CURRENT_PAGE,
    SET_CURRENT_POST,
    ADD_POST
}